name: Generate Instrument Table of Contents
run-name: Generate Instrument Table of Contents

on: 
  release:
  workflow_dispatch:
  push:
    paths:
      - "gh-actions-generate-toc.py"
      - ".github/workflows/generate-toc.yml"

concurrency:
  group: ${{ github.workflow }}
  cancel-in-progress: true

permissions:
  contents: write

jobs:
  generate-instrument-toc:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          ref: main

      - name: Prepare Python environment
        uses: actions/setup-python@v5
        with:
          python-version: 3.11

      - name: Install dependencies
        run: pip install -U requests boto3

      - name: Generate Instrument Table of Contents
        run: python gh-actions-generate-toc.py
        id: generate-toc
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          DOWNLOAD_URL_PREFIX: "https://s3.muse-sounds.work/"
          ENDPOINT_URL: ${{ secrets.ENDPOINT_URL }}
          ACCESS_KEY: ${{ secrets.ACCESS_KEY }}
          SECRET_KEY: ${{ secrets.SECRET_KEY }}
          BUCKET_NAME: "muse-sounds"

      - name: Commit and push changes
        uses: actions4git/add-commit-push@v1
        if: ${{ steps.generate-toc.outputs.continue_commit != 'false' }}
        with:
          commit-message: ${{ steps.generate-toc.outputs.commit_message }}
